Listen 5000
Listen 35357

<VirtualHost *:5000>
    WSGIDaemonProcess keystone-public user=keystone group=keystone processes=4 threads=1
    WSGIProcessGroup keystone-public
    WSGIScriptAlias / /usr/local/bin/keystone-wsgi-public
    <Directory /usr/local/bin>
        Require all granted
    </Directory>
    ErrorLog /var/log/keystone/keystone-apache-error.log
    CustomLog /var/log/keystone/keystone-apache-access.log combined
</VirtualHost>

<VirtualHost *:35357>
    WSGIDaemonProcess keystone-admin user=keystone group=keystone processes=4 threads=1
    WSGIProcessGroup keystone-admin
    WSGIScriptAlias / /usr/local/bin/keystone-wsgi-admin
    <Directory /usr/local/bin>
        Require all granted
    </Directory>
    ErrorLog /var/log/keystone/keystone-admin-error.log
    CustomLog /var/log/keystone/keystone-admin-access.log combined
</VirtualHost>
