Listen 5000

<VirtualHost *:5000>
    WSGIDaemonProcess keystone user=keystone group=keystone processes=4 threads=1
    WSGIProcessGroup keystone
    WSGIScriptAlias / /usr/local/bin/keystone-wsgi-public
    <Directory /usr/local/bin>
        Require all granted
    </Directory>
    ErrorLog /var/log/keystone/keystone-apache-error.log
    CustomLog /var/log/keystone/keystone-apache-access.log combined
</VirtualHost>
